name = "GhibliPalettes"
uuid = "90723813-cdbc-4127-ac5b-633cd2ebf9f7"
authors = ["jdiaz97 <josediazrrnn@gmail.com>"]
version = "0.1.5"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
julia = "1"
Colors = "0.12"
ColorSchemes = "3"